VTMUnitTest.runAll

VTMUnitTest.runTestForClass(VTMParameter, true);
VTMUnitTest.runTestForClass(VTMContext, true);

VTMUnitTest.reportAllErrors = true;

VTMUnitTest.runTest("TestVTMContext:test_OSCCommunication")

VTMUnitTest.runTest("TestVTMParameter:test_GetAttributes")
VTMParameter.test
VTMValueParameter.test

AbstractResponderFunc.allFuncProxies
AbstractResponderFunc.allEnabled['OSC unmatched'][0].free
